blueprint:
  name: Ligar luzes e switches com presença e horário (bloqueio por modo)
  description: >
    Liga luzes e switches ao detectar presença, apenas dentro de um horário específico,
    e se um modo (input_boolean) de bloqueio estiver desligado.
  domain: automation
  input:
    sensor_presenca:
      name: Sensor de presença
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
            - presence

    luzes:
      name: Luzes a ligar (opcional)
      default: []
      selector:
        entity:
          domain: light
          multiple: true

    switches:
      name: Switches a ligar (opcional)
      default: []
      selector:
        entity:
          domain: switch
          multiple: true

    modo_bloqueio:
      name: Modo que desativa a automação (input_boolean)
      description: Se este modo estiver ativado, a automação será ignorada.
      selector:
        entity:
          domain: input_boolean

    horario_inicio:
      name: Início do horário permitido
      default: "06:00:00"
      selector:
        time: {}

    horario_fim:
      name: Fim do horário permitido
      default: "22:00:00"
      selector:
        time: {}

trigger:
  - platform: state
    entity_id: !input sensor_presenca
    to: "on"

condition:
  - condition: time
    after: !input horario_inicio
    before: !input horario_fim

  - condition: state
    entity_id: !input modo_bloqueio
    state: "off"

action:
  - if:
      - condition: template
        value_template: "{{ luzes is defined and luzes | length > 0 }}"
    then:
      - service: light.turn_on
        data: {}
        target:
          entity_id: !input luzes

  - if:
      - condition: template
        value_template: "{{ switches is defined and switches | length > 0 }}"
    then:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: !input switches

mode: single
