blueprint:
  name: Ligar Luzes e Switches com Presença (Modo e Horário Opcionais)
  description: >
    Liga luzes e/ou switches automaticamente ao detectar presença ou movimento,
    com suporte a restrições por modo (input_boolean) e/ou horário.
  domain: automation
  input:
    sensores_presenca:
      name: Sensores de presença, ocupação ou movimento
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
            - presence
          multiple: true

    luzes:
      name: Luzes a ligar
      selector:
        entity:
          domain: light
          multiple: true

    switches:
      name: Switches a ligar (opcional)
      default: []
      selector:
        entity:
          domain: switch
          multiple: true

    usar_modo:
      name: Restringir por modo?
      default: false
      selector:
        boolean: {}

    modo_booleano:
      name: Modo (input_boolean) necessário
      default: ""
      selector:
        entity:
          domain: input_boolean

    usar_horario:
      name: Restringir por horário?
      default: false
      selector:
        boolean: {}

    horario_inicio:
      name: Início do horário permitido
      default: "18:00:00"
      selector:
        time: {}

    horario_fim:
      name: Fim do horário permitido
      default: "06:00:00"
      selector:
        time: {}

trigger:
  - platform: state
    entity_id: !input sensores_presenca
    to: "on"

condition:
  - condition: and
    conditions:
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ not (input.usar_modo | bool) }}"
          - condition: state
            entity_id: !input modo_booleano
            state: "on"

      - condition: or
        conditions:
          - condition: template
            value_template: "{{ not (input.usar_horario | bool) }}"
          - condition: time
            after: !input horario_inicio
            before: !input horario_fim

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ input.luzes | length > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input luzes

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ input.switches | length > 0 }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switches

mode: restart
