blueprint:
  name: Ligar Luzes e Switches com Presença (com Modos e Horário Opcionais)
  description: >
    Liga luzes e/ou switches automaticamente ao detectar presença ou movimento.
    Permite restrições por horário, modo ativado e modo que desabilita.
  domain: automation
  input:
    sensores_presenca:
      name: Sensores de presença, ocupação ou movimento
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
            - presence
          multiple: true

    luzes:
      name: Luzes a ligar
      selector:
        entity:
          domain: light
          multiple: true

    switches:
      name: Switches a ligar (opcional)
      default: []
      selector:
        entity:
          domain: switch
          multiple: true

    modo_ativado:
      name: Somente se este modo estiver ligado (opcional)
      default: ""
      selector:
        entity:
          domain: input_boolean

    modo_desabilitado:
      name: Não executar se este modo estiver ligado (opcional)
      default: ""
      selector:
        entity:
          domain: input_boolean

    usar_horario:
      name: Restringir por horário?
      default: false
      selector:
        boolean: {}

    horario_inicio:
      name: Início do horário permitido
      default: ""
      selector:
        time: {}

    horario_fim:
      name: Fim do horário permitido
      default: ""
      selector:
        time: {}

trigger:
  - platform: state
    entity_id: !input sensores_presenca
    to: "on"

condition:
  - condition: and
    conditions:

      # Condição: se um modo deve estar ligado
      - condition: template
        value_template: >
          {% if modo_ativado != '' %}
            {{ is_state(modo_ativado, 'on') }}
          {% else %}
            true
          {% endif %}

      # Condição: se um modo deve estar desligado (bloqueio)
      - condition: template
        value_template: >
          {% if modo_desabilitado != '' %}
            {{ is_state(modo_desabilitado, 'off') }}
          {% else %}
            true
          {% endif %}

      # Condição opcional: dentro do horário com suporte a madrugada
      - condition: template
        value_template: >
          {% if not usar_horario %}
            true
          {% else %}
            {% set start = strptime(horario_inicio, '%H:%M:%S').time() if horario_inicio != "" else None %}
            {% set end = strptime(horario_fim, '%H:%M:%S').time() if horario_fim != "" else None %}
            {% set now = now().time() %}
            {% if start and end %}
              {% if start < end %}
                {{ start <= now <= end }}
              {% else %}
                {{ now >= start or now <= end }}
              {% endif %}
            {% else %}
              true
            {% endif %}
          {% endif %}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ luzes | length > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input luzes

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ switches | length > 0 }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switches

mode: restart
