blueprint:
  name: LUZES_E_SWITCHES_-_OFF_presença_hora(+)_modo(-)
  description: >
    Desliga luzes e switches após ausência de presença por um tempo definido.
    A automação só roda se estiver dentro do intervalo de horário configurado e o modo de bloqueio estiver desligado.
  domain: automation
  input:
    sensor_presenca:
      name: Sensor de presença
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
            - presence

    luzes:
      name: Luzes a desligar
      selector:
        entity:
          domain: light
          multiple: true

    switches:
      name: Switches a desligar (opcional)
      default: []
      selector:
        entity:
          domain: switch
          multiple: true

    tempo_ausencia:
      name: Tempo sem presença (segundos)
      default: 30
      selector:
        number:
          min: 5
          max: 600
          unit_of_measurement: seconds
          mode: slider

    modo_bloqueio:
      name: Modo de bloqueio (input_boolean) — opcional
      default: null
      selector:
        entity:
          domain: input_boolean

    horario_inicio:
      name: Horário de início (formato 24h)
      default: "00:00:00"
      selector:
        time: {}

    horario_fim:
      name: Horário de fim (formato 24h)
      default: "23:59:59"
      selector:
        time: {}

trigger:
  - platform: state
    entity_id: !input sensor_presenca
    to: "off"
    for:
      seconds: !input tempo_ausencia

condition:
  - condition: template
    value_template: >-
      {% set modo = inputs.modo_bloqueio %}
      {{ not modo or not is_state(modo, 'on') }}

  - condition: template
    value_template: >-
      {% set inicio = inputs.horario_inicio %}
      {% set fim = inputs.horario_fim %}
      {{ now().strftime('%H:%M:%S') >= inicio and now().strftime('%H:%M:%S') <= fim }}

action:
  - service: light.turn_off
    target:
      entity_id: !input luzes

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ inputs.switches | length > 0 }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input switches

mode: single
