blueprint:
  name: LUZES_E_SWITCHES_-_ON_presença_hora(+)_modo(-)
  description: >
    Liga luzes e/ou switches quando detectar presença,
    apenas dentro do horário definido e se o modo bloqueador estiver desligado.
  domain: automation
  input:
    sensor_presenca:
      name: Sensor de presença
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
            - presence

    luzes:
      name: Luzes a ligar (opcional)
      default: []
      selector:
        entity:
          domain: light
          multiple: true

    switches:
      name: Switches a ligar (opcional)
      default: []
      selector:
        entity:
          domain: switch
          multiple: true

    modo_bloqueio:
      name: Modo de bloqueio (input_boolean)
      description: A automação será ignorada se esse modo estiver ativado.
      selector:
        entity:
          domain: input_boolean

    horario_inicio:
      name: Horário de início
      default: "00:00:00"
      selector:
        time: {}

    horario_fim:
      name: Horário de fim
      default: "23:59:59"
      selector:
        time: {}

trigger:
  - platform: state
    entity_id: !input sensor_presenca
    to: "on"

condition:
  - condition: time
    after: !input horario_inicio
    before: !input horario_fim
  - condition: state
    entity_id: !input modo_bloqueio
    state: "off"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ (not is_state('!input luzes', [])) }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input luzes

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ (not is_state('!input switches', [])) }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switches

mode: single
