blueprint:
  name: Desligar Equipamentos ao Ativar Modo
  description: >
    Desliga luzes, ventiladores, TVs, tomadas e ar-condicionado ao ativar um modo como "ausente".
    Opcionalmente envia uma mensagem pela Alexa via script personalizado.
  domain: automation
  input:
    modo_booleano:
      name: Booleano do modo (ex: modo ausente)
      selector:
        entity:
          domain: input_boolean

    luzes:
      name: Luzes a desligar
      selector:
        entity:
          domain: light
          multiple: true

    ventiladores:
      name: Ventiladores a desligar
      selector:
        entity:
          domain: fan
          multiple: true

    tvs:
      name: TVs a desligar
      selector:
        entity:
          domain: switch
          multiple: true

    tomadas:
      name: Tomadas a desligar
      selector:
        entity:
          domain: switch
          multiple: true

    ar_condicionado:
      name: Ar-condicionado (com checagem de estado)
      selector:
        entity:
          domain: climate

    script_fala:
      name: Script para anúncio na Alexa (opcional)
      default: ""
      selector:
        entity:
          domain: script

    mensagem:
      name: Mensagem para Alexa (opcional)
      default: ""
      selector:
        text: {}

    dispositivos_alexa:
      name: Dispositivos Alexa (opcional)
      default: []
      selector:
        entity:
          domain: media_player
          multiple: true

    volume:
      name: Volume da Alexa (opcional)
      default: 0.5
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
          unit_of_measurement: ""

trigger:
  - platform: state
    entity_id: !input modo_booleano
    from: "off"
    to: "on"

condition: []

action:
  - service: light.turn_off
    target:
      entity_id: !input luzes
  - service: fan.turn_off
    target:
      entity_id: !input ventiladores
  - service: switch.turn_off
    target:
      entity_id: !input tvs
  - service: switch.turn_off
    target:
      entity_id: !input tomadas

  - condition: state
    entity_id: !input ar_condicionado
    state: cooling
  - service: climate.turn_off
    target:
      entity_id: !input ar_condicionado

  - if:
      - condition: template
        value_template: "{{ script_fala != '' and mensagem != '' }}"
    then:
      - service: !input script_fala
        data:
          mensagem: !input mensagem
          onde_anunciar: !input dispositivos_alexa
          volume: !input volume

mode: single
