blueprint:
  name: "Notificação de Entrada/Saída de Zona"
  description: "Envia notificação quando uma pessoa entra ou sai de uma zona específica"
  domain: automation
  input:
    person_entity:
      name: Pessoa
      description: "Selecione a entidade da pessoa"
      selector:
        entity:
          domain: person
    zone_entity:
      name: Zona
      description: "Selecione a entidade da zona"
      selector:
        entity:
          domain: zone
    notify_service:
      name: Serviço de Notificação
      description: "Selecione o serviço de notificação (ex: notify.mobile_app_seu_celular)"
      selector:
        entity:
          domain: notify
    message_enter:
      name: "Mensagem de Entrada"
      description: "Mensagem quando a pessoa ENTRA na zona. Use {person} e {zone} como placeholders"
      default: "{person} entrou na zona {zone}"
      selector:
        text:
    message_leave:
      name: "Mensagem de Saída"
      description: "Mensagem quando a pessoa SAI da zona. Use {person} e {zone} como placeholders"
      default: "{person} saiu da zona {zone}"
      selector:
        text:

variables:
  person_name: "{{ states[input.person_entity].name }}"
  zone_name: "{{ states[input.zone_entity].name }}"

trigger:
  - platform: state
    entity_id: !input person_entity
    # Dispara quando a pessoa entra na zona
    to: "{{ states[input.zone_entity].name }}"
  - platform: state
    entity_id: !input person_entity
    # Dispara quando a pessoa sai da zona
    from: "{{ states[input.zone_entity].name }}"

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == zone_name }}"
        sequence:
          - service: !input notify_service
            data:
              message: >
                {{ 
                  (input.message_enter 
                  | replace('{person}', person_name) 
                  | replace('{zone}', zone_name))
                }}
      - conditions:
          - condition: template
            value_template: "{{ trigger.from_state.state == zone_name }}"
        sequence:
          - service: !input notify_service
            data:
              message: >
                {{ 
                  (input.message_leave 
                  | replace('{person}', person_name) 
                  | replace('{zone}', zone_name))
                }}
